



	<style>
		body { font-size: 100%; }
		label, input { display:block; }
		input.text { margin-bottom:12px; width:95%; padding: .4em; }
		fieldset { padding:0; border:0; margin-top:25px; }
		h1 { font-size: 1.2em; margin: .6em 0; }
		div#users-contain { width: 350px; margin: 20px 0; }
		div#users-contain table { margin: 1em 0; border-collapse: collapse; width: 100%; }
		div#users-contain table td, div#users-contain table th { border: 1px solid #eee; padding: .6em 10px; text-align: left; }
		.ui-dialog .ui-state-error { padding: .3em; }
		.validateTips { border: 1px solid transparent; padding: 0.3em; }
		.labelleft{ 
			display: inline-block; 
			width: 60px; 
			text-align: right; 
			color: #666666; 
			font-weight: bold;
		}
		
		/*  Portables */
		.column { width: 220px; float: left; padding-bottom: 100px;}
		.portlet { margin: 0 0.5em 0.5em 0; }
		.portlet-header { margin: 0.3em; padding-bottom: 4px; padding-left: 0.2em; }
		.portlet-header .ui-icon { float: right; }
		.portlet-content { padding: 0.4em; }
		.ui-sortable-placeholder { border: 1px dotted black; visibility: visible !important; height: 50px !important; }
		.ui-sortable-placeholder * { visibility: hidden; }		
		
		.spalte-header{ font-size: 1.3em; font-weight: bold; text-align: center}
		.spalte{ 
			border-right: 1px solid #999999; 
			padding-left: 0.5em; 
			padding-right: 0px; 
		}
		
		.spalte1{ background-color: #E6E6FA; } /*lavender*/
		.spalte2{ background-color: #F0FFFF; } /* azure */
		.spalte3{ background-color: #FFEFD5; } /* snow */
		
		.clear{clear:both;}
		
		
	</style>

	<script>
	$(function() {
		// a workaround for a flaw in the demo system (http://dev.jqueryui.com/ticket/4375), ignore!
		$( "#dialog:ui-dialog" ).dialog( "destroy" );
  
		var name = $( "#name" ),
			email = $( "#email" ),
			password = $( "#password" ),
			allFields = $( [] ).add( name ).add( email ).add( password ),
			tips = $( ".validateTips" );				

		function updateTips( t ) {
			tips
				.text( t )
				.addClass( "ui-state-highlight" );
			setTimeout(function() {
				tips.removeClass( "ui-state-highlight", 1500 );
			}, 500 );
		}

		function checkLength( o, n, min, max ) {
			if ( o.val().length > max || o.val().length < min ) {
				o.addClass( "ui-state-error" );
				updateTips( "Die Länge von " + n + " muss zwischen " +
					min + " und " + max + " sein." );
				return false;
			} else {
				return true;
			}
		}

		function checkRegexp( o, regexp, n ) {
			if ( !( regexp.test( o.val() ) ) ) {
				o.addClass( "ui-state-error" );
				updateTips( n );
				return false;
			} else {
				return true;
			}
		}
		
		$( "#dialog-form-user" ).dialog({
			autoOpen: false,
			height: 300,
			width: 350,
			modal: true,
			buttons: {
				"Benutzerkonto anlegen": function() {
				name = $( "#name" ),
				email = $( "#email" ),
				password = $( "#password" ),
				allFields = $( [] ).add( name ).add( email ).add( password ),
				tips = $( ".validateTips" );				
					var bValid = true;
					allFields.removeClass( "ui-state-error" );

					bValid = bValid && checkLength( name, "username", 3, 16 );
					bValid = bValid && checkLength( email, "email", 6, 80 );
					bValid = bValid && checkLength( password, "password", 5, 16 );

					bValid = bValid && checkRegexp( name, /^[a-z]([0-9a-z_])+$/i, "Username may consist of a-z, 0-9, underscores, begin with a letter." );
					// From jquery.validate.js (by joern), contributed by Scott Gonzalez: http://projects.scottsplayground.com/email_address_validation/
					bValid = bValid && checkRegexp( email, /^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i, "eg. ui@jquery.com" );
					bValid = bValid && checkRegexp( password, /^([0-9a-zA-Z])+$/, "Password field only allow : a-z 0-9" );

					if ( bValid ) {
						$( "#users tbody" ).append( "<tr>" +
							"<td>" + name.val() + "</td>" + 
							"<td>" + email.val() + "</td>" + 
							"<td>" + password.val() + "</td>" +
						"</tr>" ); 
						$( this ).dialog( "close" );
					}
				},
				Cancel: function() {
					$( this ).dialog( "close" );
				}
			},
			close: function() {
				allFields.val( "" ).removeClass( "ui-state-error" );
			}
		});

		function GetFormName( id ){
			return '/form-'+$( id ).attr('name') + '.html'
		}
		
		$( "#create-user" )
			.button()
			.click(function() {
				$("#dialog-form-user").load( GetFormName( "#create-user" ), function(data){
					$( "#dialog-form-user" ).dialog( "open" );
				});
			});

			
			
		/* Boxen */	
		
		$( ".column" ).sortable({		
			connectWith: ".column"
			,cancel: ".spalte-header"
			
					
		});
	


		$( ".portlet" ).addClass( "ui-widget ui-widget-content ui-helper-clearfix ui-corner-all" )
			.find( ".portlet-header" )
				.addClass( "ui-widget-header ui-corner-all" )
				.prepend( "<span class='ui-icon ui-icon-minusthick'></span>")
				.end()
			.find( ".portlet-content" );

		$( ".portlet-header .ui-icon" ).click(function() {
			$( this ).toggleClass( "ui-icon-minusthick" ).toggleClass( "ui-icon-plusthick" );
			$( this ).parents( ".portlet:first" ).find( ".portlet-content" ).toggle();
		});

		
	
		$( ".column" ).disableSelection();			
	});
	</script>

	
<div id="dialog-form-user" title="Neue zzForm" alt="so ist das"></div>

<div class="clear"></div>
	<a id="create-user" alt="nichts" name="create-user" href="#">Erstelle Form</a>

<?php

$title = 'Bereiche';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url( 'bereich', array( 'action'=>'add'));?>">Neuen Form zuf&uuml;gen</a>
 </p>

 <table class="table">
 <tr>
     <th>ID</th>
     <th>Formname</th>
     <th>Feldname</th>
     <th>TB-Feldname</th>
	 <th>Bezeichnung</th>
     <th>Sort.</th>
     <th>Gruppe</th>
     <th>Typ</th>
     <th>CSS-ID</th>
     <th>CSS-Name</th>
     <th>Lookup Tabelle</th>
     <th>Lookup Fld-Bez</th>
     <th>Lookup Fld-Id</th>
     <th>Optionvalues</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($zzforms as $zzForm) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($zzForm->id);?></td>
     <td><?php echo $this->escapeHtml($zzForm->formname);?></td>
     <td><?php echo $this->escapeHtml($zzForm->feldname);?></td>
     <td><?php echo $this->escapeHtml($zzForm->tbfeldname);?></td>
	 <td><?php echo $this->escapeHtml($zzForm->bezeichnung);?></td>
     <td><?php echo $this->escapeHtml($zzForm->sort);?></td>
     <td><?php echo $this->escapeHtml($zzForm->gruppe);?></td>
     <td><?php echo $this->escapeHtml($zzForm->typ);?></td>
     <td><?php echo $this->escapeHtml($zzForm->cssid);?></td>
     <td><?php echo $this->escapeHtml($zzForm->cssname);?></td>
     <td><?php echo $this->escapeHtml($zzForm->lookuptable);?></td>
     <td><?php echo $this->escapeHtml($zzForm->lookupfldbezeichnung);?></td>
     <td><?php echo $this->escapeHtml($zzForm->lookupfldid);?></td>
     <td><?php echo $this->escapeHtml($zzForm->optionvalues);?></td>
     <td>
         <a href="<?php echo $this->url('bereich', array('action'=>'edit', 'id' => $bereich->id));?>">&Auml;ndern</a>
         <a href="<?php echo $this->url('bereich', array('action'=>'delete', 'id' => $bereich->id));?>">L&ouml;schen</a>
     </td>
 </tr>
 <?php endforeach; ?>
 
 <?php 
/*	use Application\Model\ZzformBuilder;
	
	$form = new ZzformBuilder('art_edit');
	$form->readDBFormData();
*/	
?>	
	
	
 
 </table>