<?php echo $this->doctype(); ?>

<html lang="en">

    <head>
	
        
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

		
		<link rel="stylesheet" href="/js/ui/development_bundle/themes/base/jquery.ui.all.css">
		<script src="/js/ui/development_bundle/jquery-1.7.2.js"></script>
		<script src="/js/ui/development_bundle/external/jquery.bgiframe-2.1.2.js"></script>
		<script src="/js/ui/development_bundle/ui/jquery.ui.core.js"></script>
		<script src="/js/ui/development_bundle/ui/jquery.ui.widget.js"></script>
		<script src="/js/ui/development_bundle/ui/jquery.ui.mouse.js"></script>
		<script src="/js/ui/development_bundle/ui/jquery.ui.button.js"></script>
		<script src="/js/ui/development_bundle/ui/jquery.ui.draggable.js"></script>
		<script src="/js/ui/development_bundle/ui/jquery.ui.position.js"></script>
		<script src="/js/ui/development_bundle/ui/jquery.ui.resizable.js"></script>
		<script src="/js/ui/development_bundle/ui/jquery.ui.dialog.js"></script>
		<script src="/js/ui/development_bundle/ui/jquery.ui.sortable.js"></script>	
		<script src="/js/ui/development_bundle/ui/jquery.effects.core.js"></script>
			<!-- link rel="stylesheet" href="/demos.css" -->	

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
						<li class=""><a href="<?php echo $this->url( 'art', array( 'action'=>'index'));?>">Arten auflisten</a></li>
						<li class=""><a href="<?php echo $this->url( 'bereich', array( 'action'=>'index'));?>">Bereiche auflisten</a></li>
						<li class=""><a href="<?php echo $this->url( 'zzform', array( 'action'=>'index'));?>">Formelemente auflisten</a></li>
						
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
				<p><a href="http://phpmyadminzf2" target="_blank">phpMyAdmin ZF2</a> - <a href="http://phpmyadmin" target="_blank">phpMyAdmin</a></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
